# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# proto-file: //system/software_defined_vehicle/middleware/service_authz/proto/sdv/authz/policy/authz_policy.proto
# proto-message: AuthzPolicy

publisher {
  message: "com.android.sdv.sample.vsidl_vhal_proxy_integration.NightMode"
  topic: "vhal-night-mode"
}

publisher {
  message: "com.android.sdv.someip.LightCommand"
  topic: "light-command"
  topic: "com-android-sdv-someip-light-command-light-command"
}

publisher {
  message: "com.sdv.google.display_safety.RangeRemaining"
  topic: "range-remaining"
  topic: "com-sdv-google-display-safety-range-remaining-range-remaining"
}

subscriber {
  message: "com.android.sdv.someip.CarlaAmbientFog"
  topic: "carla-ambient-fog"
}

subscriber {
  message: "com.android.sdv.someip.CarlaAmbientLight"
  topic: "carla-ambient-light"
}

subscriber {
  message: "com.android.sdv.sample.gapb.RechargeCommand"
  topic: "recharge-command"
}

subscriber {
  message: "com.android.sdv.someip.CarlaVehicleOdometer"
  topic: "odometer-reading"
}


##############
# ACL Legacy #
##############
acls { name: "Reader" include: "*" }
service_units { name: "com-android-sdv-sample-vsidl-vhal-proxy-integration-night-mode-vhal-night-mode" acl_names: "Reader" }
service_units { name: "com-android-sdv-someip-light-command-light-command" acl_names: "Reader" }
service_units { name: "light-command" acl_names: "Reader" }
service_units { name: "com-sdv-google-display-safety-range-remaining-range-remaining" acl_names: "Reader" }
service_units { name: "range-remaining" acl_names: "Reader" }


