// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//! WARNING: DO NOT EDIT.
//! WARNING: This file is generated by VSIDL middleware code generator.
//! WARNING: Changes will be overwritten when the file is regenerated.

/// Namespace for publication descriptors available to the service bundle.
pub struct PublisherDescriptors<Proto>(std::marker::PhantomData<Proto>);

impl PublisherDescriptors<someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog> {
    /// Publisher descriptor 'carla-ambient-fog' of 'com.android.sdv.someip.CarlaAmbientFog'
    pub const CARLA_AMBIENT_FOG: &sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("carla-ambient-fog")
            .with_message("com.android.sdv.someip.CarlaAmbientFog")
            .with_service_unit_name("com-android-sdv-someip-carla-ambient-fog-carla-ambient-fog")
            .with_capacity(8)
            .with_max_message_size(2)
    };

    /// List of all publisher descriptors of 'com.android.sdv.someip.CarlaAmbientFog' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog,
    >] = &[Self::CARLA_AMBIENT_FOG];
}
impl PublisherDescriptors<someip_messages_catalog::carla_ambient_light::CarlaAmbientLight> {
    /// Publisher descriptor 'carla-ambient-light' of 'com.android.sdv.someip.CarlaAmbientLight'
    pub const CARLA_AMBIENT_LIGHT: &sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::carla_ambient_light::CarlaAmbientLight,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("carla-ambient-light")
            .with_message("com.android.sdv.someip.CarlaAmbientLight")
            .with_service_unit_name(
                "com-android-sdv-someip-carla-ambient-light-carla-ambient-light",
            )
            .with_capacity(8)
            .with_max_message_size(2)
    };

    /// List of all publisher descriptors of 'com.android.sdv.someip.CarlaAmbientLight' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::carla_ambient_light::CarlaAmbientLight,
    >] = &[Self::CARLA_AMBIENT_LIGHT];
}
impl PublisherDescriptors<vhal_proxy_catalog::night_mode::NightMode> {
    /// Publisher descriptor 'vhal-night-mode' of 'com.android.sdv.sample.vsidl_vhal_proxy_integration.NightMode'
    pub const VHAL_NIGHT_MODE: &sdv::mw::clientlib::PublisherDescriptor<
        vhal_proxy_catalog::night_mode::NightMode,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("vhal-night-mode")
            .with_message("com.android.sdv.sample.vsidl_vhal_proxy_integration.NightMode")
            .with_service_unit_name(
                "com-android-sdv-sample-vsidl-vhal-proxy-integration-night-mode-vhal-night-mode",
            )
            .with_capacity(8)
            .with_max_message_size(2)
    };

    /// List of all publisher descriptors of 'com.android.sdv.sample.vsidl_vhal_proxy_integration.NightMode' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        vhal_proxy_catalog::night_mode::NightMode,
    >] = &[Self::VHAL_NIGHT_MODE];
}
impl PublisherDescriptors<someip_messages_catalog::light_command::LightCommand> {
    /// Publisher descriptor 'light-command' of 'com.android.sdv.someip.LightCommand'
    pub const LIGHT_COMMAND: &sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::light_command::LightCommand,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("light-command")
            .with_message("com.android.sdv.someip.LightCommand")
            .with_service_unit_name("com-android-sdv-someip-light-command-light-command")
            .with_capacity(8)
            .with_max_message_size(8)
    };

    /// List of all publisher descriptors of 'com.android.sdv.someip.LightCommand' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::light_command::LightCommand,
    >] = &[Self::LIGHT_COMMAND];
}
impl PublisherDescriptors<car_controller_proto::recharge_command::RechargeCommand> {
    /// Publisher descriptor 'recharge-command' of 'com.android.sdv.sample.gapb.RechargeCommand'
    pub const RECHARGE_COMMAND: &sdv::mw::clientlib::PublisherDescriptor<
        car_controller_proto::recharge_command::RechargeCommand,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("recharge-command")
            .with_message("com.android.sdv.sample.gapb.RechargeCommand")
            .with_service_unit_name("com-android-sdv-sample-gapb-recharge-command-recharge-command")
            .with_capacity(8)
            .with_max_message_size(13)
    };

    /// List of all publisher descriptors of 'com.android.sdv.sample.gapb.RechargeCommand' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        car_controller_proto::recharge_command::RechargeCommand,
    >] = &[Self::RECHARGE_COMMAND];
}
impl PublisherDescriptors<someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer> {
    /// Publisher descriptor 'odometer-reading' of 'com.android.sdv.someip.CarlaVehicleOdometer'
    pub const ODOMETER_READING: &sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("odometer-reading")
            .with_message("com.android.sdv.someip.CarlaVehicleOdometer")
            .with_service_unit_name(
                "com-android-sdv-someip-carla-vehicle-odometer-odometer-reading",
            )
            .with_capacity(8)
            .with_max_message_size(11)
    };

    /// List of all publisher descriptors of 'com.android.sdv.someip.CarlaVehicleOdometer' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer,
    >] = &[Self::ODOMETER_READING];
}
impl PublisherDescriptors<someip_messages_catalog::vehicledata::RangeRemaining> {
    /// Publisher descriptor 'range-remaining' of 'com.sdv.google.display_safety.RangeRemaining'
    pub const RANGE_REMAINING: &sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::vehicledata::RangeRemaining,
    > = {
        &sdv::mw::clientlib::PublisherDescriptor::new("range-remaining")
            .with_message("com.sdv.google.display_safety.RangeRemaining")
            .with_service_unit_name("com-sdv-google-display-safety-range-remaining-range-remaining")
            .with_capacity(8)
            .with_max_message_size(5)
    };

    /// List of all publisher descriptors of 'com.sdv.google.display_safety.RangeRemaining' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::PublisherDescriptor<
        someip_messages_catalog::vehicledata::RangeRemaining,
    >] = &[Self::RANGE_REMAINING];
}

/// Namespace for subscription descriptors available to the service bundle.
pub struct SubscriberDescriptors<Proto>(std::marker::PhantomData<Proto>);

impl SubscriberDescriptors<someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog> {
    /// Subscriber descriptor 'carla-ambient-fog' of 'com.android.sdv.someip.CarlaAmbientFog'
    pub const CARLA_AMBIENT_FOG: &sdv::mw::clientlib::SubscriberDescriptor<
        someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog,
    > = &sdv::mw::clientlib::SubscriberDescriptor::new("carla-ambient-fog")
        .with_message("com.android.sdv.someip.CarlaAmbientFog");

    /// List of all subscriber descriptors of 'com.android.sdv.someip.CarlaAmbientFog' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::SubscriberDescriptor<
        someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog,
    >] = &[Self::CARLA_AMBIENT_FOG];
}
impl SubscriberDescriptors<someip_messages_catalog::carla_ambient_light::CarlaAmbientLight> {
    /// Subscriber descriptor 'carla-ambient-light' of 'com.android.sdv.someip.CarlaAmbientLight'
    pub const CARLA_AMBIENT_LIGHT: &sdv::mw::clientlib::SubscriberDescriptor<
        someip_messages_catalog::carla_ambient_light::CarlaAmbientLight,
    > = &sdv::mw::clientlib::SubscriberDescriptor::new("carla-ambient-light")
        .with_message("com.android.sdv.someip.CarlaAmbientLight");

    /// List of all subscriber descriptors of 'com.android.sdv.someip.CarlaAmbientLight' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::SubscriberDescriptor<
        someip_messages_catalog::carla_ambient_light::CarlaAmbientLight,
    >] = &[Self::CARLA_AMBIENT_LIGHT];
}
impl SubscriberDescriptors<car_controller_proto::recharge_command::RechargeCommand> {
    /// Subscriber descriptor 'recharge-command' of 'com.android.sdv.sample.gapb.RechargeCommand'
    pub const RECHARGE_COMMAND: &sdv::mw::clientlib::SubscriberDescriptor<
        car_controller_proto::recharge_command::RechargeCommand,
    > = &sdv::mw::clientlib::SubscriberDescriptor::new("recharge-command")
        .with_message("com.android.sdv.sample.gapb.RechargeCommand");

    /// List of all subscriber descriptors of 'com.android.sdv.sample.gapb.RechargeCommand' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::SubscriberDescriptor<
        car_controller_proto::recharge_command::RechargeCommand,
    >] = &[Self::RECHARGE_COMMAND];
}
impl SubscriberDescriptors<someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer> {
    /// Subscriber descriptor 'odometer-reading' of 'com.android.sdv.someip.CarlaVehicleOdometer'
    pub const ODOMETER_READING: &sdv::mw::clientlib::SubscriberDescriptor<
        someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer,
    > = &sdv::mw::clientlib::SubscriberDescriptor::new("odometer-reading")
        .with_message("com.android.sdv.someip.CarlaVehicleOdometer");

    /// List of all subscriber descriptors of 'com.android.sdv.someip.CarlaVehicleOdometer' available to the service bundle
    pub const ALL_VARIANTS: &[&sdv::mw::clientlib::SubscriberDescriptor<
        someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer,
    >] = &[Self::ODOMETER_READING];
}

/// Service bundle
pub struct CarController {
    _comms: std::sync::Arc<dyn sdv::mw::Communicate>,
}

impl CarController {
    /// Creates a new instance of the service bundle
    #[deprecated(since = "2.0.0", note = "please use `builder` instead")]
    pub async fn new(
        comms: std::sync::Arc<dyn sdv::mw::Communicate>,
    ) -> sdv::status::SdvResult<Self> {
        let service = Self { _comms: comms.clone() };
        Ok(service)
    }

    /// returns a Builder for CarController
    pub fn builder() -> CarControllerBuilder {
        CarControllerBuilder::default()
    }
}

#[derive(Clone, Default)]
/// builder for CarController
pub struct CarControllerBuilder {
    comms: Option<std::sync::Arc<dyn sdv::mw::Communicate>>,
}

impl CarControllerBuilder {
    /// Sets the communication layer for the `CarController`.
    ///
    /// # Arguments
    /// * `comms` - An `Arc` pointing to a `Communicate` trait object.
    pub fn set_comms(mut self, comms: std::sync::Arc<dyn sdv::mw::Communicate>) -> Self {
        self.comms = Some(comms);
        self
    }
    /// Creates an instance of `CarController`.
    ///
    /// # Errors
    /// Returns an `SdvStatus` with `SdvStatusCode::InvalidArgument` if `comms` has not been set.
    pub async fn build(self) -> sdv::status::SdvResult<CarController> {
        let comms = self.comms.ok_or_else(|| {
            sdv::status::SdvStatus::with_message(
                sdv::status::SdvStatusCode::InvalidArgument,
                "No comms is found in CarControllerBuilder",
            )
        })?;

        let service = CarController { _comms: comms.clone() };

        Ok(service)
    }
}
