// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//! WARNING: DO NOT EDIT.
//! WARNING: This file is generated by VSIDL middleware code generator.
//! WARNING: Changes will be overwritten when the file is regenerated.

//! Shared library implementing 'CarController' service bundle logic.

#![allow(unused_imports)]
use car_controller_proto::recharge_command::RechargeCommand;
use futures::{future, stream, Stream};
use futures_util::stream::StreamExt;
use log::{debug, error, info, warn};
use someip_messages_catalog::vehicledata::RangeRemaining;
use sdv::mw::clientlib::{
    create_observer, create_publisher, create_registration_event_stream, IntoSubscriberAttributes,
};
use sdv::mw::RpcClient;
use sdv::mw::SdvComms;
use sdv::mw::{clientlib, Availability, Communicate, SubscribeOptions};
use sdv::status::{SdvResult, SdvStatus, SdvStatusCode};
use someip_messages_catalog::carla_ambient_fog::CarlaAmbientFog;
use someip_messages_catalog::carla_ambient_light::CarlaAmbientLight;
use someip_messages_catalog::carla_vehicle_odometer::CarlaVehicleOdometer;
use someip_messages_catalog::light_command::LightCommand;
use std::fmt::Debug;
use std::pin::Pin;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tap::Pipe;
use tokio::sync::watch;
use tokio::time::sleep;
use tokio_stream::wrappers::WatchStream;
use tokio_util::sync::CancellationToken;
use vhal_proxy_catalog::night_mode::NightMode;

sdv::lifecycle::register_service_bundle!(CarControllerServiceBundle);

struct CarControllerServiceBundle {
    cancellation_token: Option<CancellationToken>,
    context: ContextRef,
}

const MAXIMUM_CAR_RANGE_METERS: f32 = 402_336.0;

#[derive(Clone, Copy, Debug)]
struct BatteryRangeRemaining(f32);
enum BatteryCommand {
    FullyRecharge,
    RecordBatteryConsumption(f32), // Records how much range was consumed in meters
}

#[derive(Clone, Copy, Debug, Default)]
struct AmbientState {
    is_fog: bool,
    is_night: bool,
}

enum AmbientUpdate {
    Fog(bool),
    Night(bool),
}

impl ServiceBundle for CarControllerServiceBundle {
    fn new(context: ContextRef) -> Self {
        if let Err(err) = sdv::tracing::try_init_tracing() {
            warn!("Failed to init service bundles tracing: {err}");
        }
        Self { cancellation_token: None, context }
    }

    fn on_start(&mut self) {
        debug!("on_start called for service bundle...");
        let context = self.context;
        let cancellation_token = CancellationToken::new();
        self.cancellation_token = Some(cancellation_token.clone());
        let Ok(runtime) =
            tokio::runtime::Builder::new_current_thread().enable_time().enable_io().build()
        else {
            panic!("Failed to start the runtime!");
        };
        debug!("spawning thread for service bundle...");
        let _ = std::thread::spawn(move || {
            runtime.block_on(async move {
                let comms = Arc::new(SdvComms{context});
                debug!("Calling sdv_main...");
                let res = tokio::select! {
                    res = sdv_main(comms) => res,
                    () = cancellation_token.cancelled() => Err(sdv::status::SdvStatus::new(sdv::status::SdvStatusCode::Cancelled)),
                };
                error!("Service bundle loop stopped: {res:?}.");
            });
            drop(runtime);
        });
    }

    fn on_stop(&mut self) {
        self.cancellation_token.as_mut().expect("Must have been created on_start").cancel();
        self.cancellation_token = None;
    }
}

async fn sdv_main(comms: Arc<SdvComms>) -> sdv::status::SdvResult<()> {
    info!("Starting service bundle 'CarController'");

    let (ambient_rx, ambient_state) = watch::channel(AmbientState::default());

    let (battery_rx, battery_state) =
        watch::channel(BatteryRangeRemaining(MAXIMUM_CAR_RANGE_METERS));

    let mut tasks = tokio::task::JoinSet::new();

    {
        let comms = comms.clone();
        tasks.spawn(async move { monitor_ambient_state(comms, ambient_rx).await });
    }

    {
        let comms = comms.clone();
        tasks.spawn(async move { monitor_battery_state(comms, battery_rx).await });
    }

    {
        let comms = comms.clone();
        let ambient_state = ambient_state.clone();
        tasks.spawn(async move { control_headlights(comms, ambient_state).await });
    }

    {
        let comms = comms.clone();
        let ambient_state = ambient_state.clone();
        tasks.spawn(async move { control_ivi_ui_night_mode(comms, ambient_state).await });
    }

    {
        let comms = comms.clone();
        tasks.spawn(async move { publish_battery_remaining_range(comms, battery_state).await });
    }

    while let Some(res) = tasks.join_next().await {
        if let Err(err) = res {
            error!("Task failed: {err:?}");
        }
    }

    Ok(())
}

async fn monitor_ambient_state(
    comms: Arc<SdvComms>,
    ambient_rx: watch::Sender<AmbientState>,
) -> SdvResult<()> {
    let light_stream = get_topic_stream(
        comms.context,
        sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::SubscriberDescriptors::<
            CarlaAmbientLight,
        >::CARLA_AMBIENT_LIGHT,
    )
    .await?
    .filter_map(|res| future::ready(res.ok().map(|update| AmbientUpdate::Night(update.is_night))));

    let fog_stream = get_topic_stream(
        comms.context,
        sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::SubscriberDescriptors::<
            CarlaAmbientFog,
        >::CARLA_AMBIENT_FOG,
    )
    .await?
    .filter_map(|res| future::ready(res.ok().map(|update| AmbientUpdate::Fog(update.is_foggy))));

    let mut combined_stream = stream::select(light_stream, fog_stream);

    while let Some(update) = combined_stream.next().await {
        ambient_rx.send_if_modified(|state| match update {
            AmbientUpdate::Fog(is_fog) => {
                let changed = state.is_fog != is_fog;
                state.is_fog = is_fog;
                changed
            }
            AmbientUpdate::Night(is_night) => {
                let changed = state.is_night != is_night;
                state.is_night = is_night;
                changed
            }
        });
    }
    Ok(())
}

async fn control_headlights(
    comms: Arc<SdvComms>,
    ambient_state: watch::Receiver<AmbientState>,
) -> SdvResult<()> {
    let headlight_command_publisher =
        create_publisher(
            comms.as_ref(),
            sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::PublisherDescriptors::<
                LightCommand,
            >::LIGHT_COMMAND,
        )
        .await?;

    let mut updates = WatchStream::new(ambient_state);

    while let Some(state) = updates.next().await {
        let command = LightCommand {
            park_lights_on: state.is_night || state.is_fog,
            fog_lights_on: state.is_fog,
            lowbeam_on: state.is_night,
            highbeam_on: state.is_night && state.is_fog,
            ..Default::default()
        };
        info!("Publishing LightCommand: {command:?}");
        headlight_command_publisher.publish(&command)?;
    }
    Ok(())
}

async fn control_ivi_ui_night_mode(
    comms: Arc<SdvComms>,
    ambient_state: watch::Receiver<AmbientState>,
) -> SdvResult<()> {
    let night_mode_publisher =
        create_publisher(
            comms.as_ref(),
            sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::PublisherDescriptors::<
                NightMode,
            >::VHAL_NIGHT_MODE,
        )
        .await?;

    let mut updates = WatchStream::new(ambient_state);

    while let Some(state) = updates.next().await {
        let command = NightMode { on: Some(state.is_night), ..Default::default() };
        info!("Publishing NightMode: {command:?}");
        night_mode_publisher.publish(&command)?;
    }
    Ok(())
}

async fn publish_battery_remaining_range(
    comms: Arc<SdvComms>,
    battery_state: watch::Receiver<BatteryRangeRemaining>,
) -> SdvResult<()> {
    let range_remaining_publisher =
        create_publisher(
            comms.as_ref(),
            sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::PublisherDescriptors::<
                RangeRemaining,
            >::RANGE_REMAINING,
        )
        .await?;
    let mut updates = WatchStream::new(battery_state);

    while let Some(new_state) = updates.next().await {
        let command = RangeRemaining { remaining_range: new_state.0, ..Default::default() };
        info!("Publishing RangeRemaining: {command:?}");
        range_remaining_publisher.publish(&command)?;
    }
    Ok(())
}

async fn monitor_battery_state(
    comms: Arc<SdvComms>,
    battery_rx: watch::Sender<BatteryRangeRemaining>,
) -> SdvResult<()> {
    let record_consumption_stream = get_topic_stream(
        comms.context,
        sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::SubscriberDescriptors::<
            CarlaVehicleOdometer,
        >::ODOMETER_READING,
    )
    .await?
    .scan(None, |prev_state: &mut Option<u64>, current_res| {
        let res = match current_res {
            Ok(current) => {
                let distance = current.distance_meters;
                let consumed = prev_state.map(|prev| distance.saturating_sub(prev)).unwrap_or(0) * 4;
                *prev_state = Some(distance);
                Some(BatteryCommand::RecordBatteryConsumption(consumed as f32))
            }
            Err(_) => None,
        };
        future::ready(Some(res))
    })
    .filter_map(future::ready);

    let recharge_command_stream = get_topic_stream(
        comms.context,
        sdv_mw_rs_com_android_sdv_sample_gapb_car_controller::SubscriberDescriptors::<
            RechargeCommand,
        >::RECHARGE_COMMAND,
    )
    .await?
    .filter_map(|res| future::ready(res.ok().map(|_| BatteryCommand::FullyRecharge)));

    let mut combined_stream = stream::select(record_consumption_stream, recharge_command_stream);

    while let Some(command) = combined_stream.next().await {
        battery_rx.send_if_modified(|state| {
            match command {
                BatteryCommand::FullyRecharge => {
                    state.0 = MAXIMUM_CAR_RANGE_METERS;
                }
                BatteryCommand::RecordBatteryConsumption(consumed) => {
                    state.0 = (state.0 - consumed).max(0.0);
                }
            }
            true
        });
    }
    Ok(())
}

fn flatten_mw<T: Send + 'static>(
    s: impl Stream<Item = SdvResult<Vec<T>>> + Send + Unpin + 'static,
) -> Pin<Box<dyn Stream<Item = SdvResult<T>> + Send>> {
    Box::pin(s.flat_map(|v| match v {
        Ok(v) => v.into_iter().map(Ok).pipe(stream::iter).left_stream(),
        Err(err) => Err(err).pipe(future::ready).pipe(stream::once).right_stream(),
    }))
}

/// Waits for topic to become available(occurs only when first publisher registers on topic),
/// then subscribes to data sent on topic. Returns a stream of data sent on topic
async fn get_topic_stream<M: protobuf::Message + Send + Debug + 'static>(
    context: ContextRef,
    descriptor: &'static clientlib::SubscriberDescriptor<M>,
) -> SdvResult<Pin<Box<dyn Stream<Item = SdvResult<M>> + Send>>> {
    let mw_comms = SdvComms { context };

    create_registration_event_stream(&mw_comms, descriptor)
        .await?
        .filter(|e| future::ready(matches!(e, &Availability::Available)))
        .pipe(Box::pin)
        .next()
        .await
        .ok_or(SdvStatus::with_message(
            SdvStatusCode::Unknown,
            "Availability stream unexpectedly closed".to_string(),
        ))?;

    create_observer(&mw_comms, descriptor, &SubscribeOptions::default())
        .await?
        .pipe(flatten_mw)
        .pipe(Ok)
}
